API tests for Publication API
BIBSYSDEV/NVA-api-testing pull request #11
Opened 2021-03-18 08:01 UTC by Eiriknil

2021-03-18 09:49 UTC, axthosarouris requested changes
Requested changed have been annotated. The rest are general comments.

2021-03-18 09:49 UTC, axthosarouris commented on tests/customers/customers.feature
> +    Scenario: GET by non-existing Customer id returns status Not Found
General comment: the identifier that we are using now is a SortableIdentifer (found in commons). It accepts UUID strings as well, so it is not a problem now, but when you will create a new resource you will not get a UUID as an identifier.

2021-03-18 09:49 UTC, axthosarouris commented on tests/registrations/registrations.feature
> +    Scenario: POST returns status Created and Resource detials
Requested change: It should also return a `Location` Header with the URI of the resource

2021-03-18 09:49 UTC, axthosarouris commented on tests/registrations/registrations.feature
> +    Scenario: GET returns status Bad Request when requesting with invalid Uuid
Requested change: ... with invalid identifier.  We do not use UUIDs anymore. We accept them but we do not use them. When we will import stuff from Cristin it is possible tha thte identifier will be only a number for the Cristin publications.

2021-03-18 09:49 UTC, axthosarouris commented on tests/registrations/registrations.feature
> +      And match response.detail == 'Identifier is not a valid UUID: ' + invalidUuid
Create a bug for it:
https://unit.atlassian.net/browse/NP-2388?atlOrigin=eyJpIjoiNTQ0MDIzZDJhNTVjNDA4ZjllNWFhZWYwNjg0Y2YyZjgiLCJwIjoiaiJ9

2021-03-18 11:13 UTC, brinxmat requested changes

2021-03-18 11:13 UTC, brinxmat commented on tests/registrations/registrations.feature
> +
We need to cover the Problem responses that we expect, Bad GW, etc. In addition, we need to be stringent about following the IETF specs for e.g. PUT, which we do not at the moment.

2021-03-18 11:19 UTC, Eiriknil commented on tests/customers/customers.feature
> +    Scenario: GET by non-existing Customer id returns status Not Found
Ok, tried to create a SortableIdentifier for a non-existing publication and get 
`{
  "title" : "Bad Request",
  "status" : 400,
  "detail" : "Identifier is not a valid UUID: 178450b5f4b-88859b77-2b77-4e35-a81a-2a54e373a84e",
  "requestId" : "fbcb3327-f45e-4d9b-ad5a-72271d4134b7"
}`

2021-03-18 11:51 UTC, Eiriknil commented on tests/registrations/registrations.feature
> +
Agree, but I need descriptions of the expected responses if I am to make tests for this.

2021-03-19 08:55 UTC, axthosarouris commented on tests/customers/customers.feature
> +    Scenario: GET by non-existing Customer id returns status Not Found
my bad. I thought we were talking about publication identifiers.

2021-03-19 08:55 UTC, axthosarouris approved these changes

2021-03-19 13:06 UTC, brinxmat approved these changes

2021-03-19 13:06 UTC, brinxmat commented on tests/registrations/registrations.feature
> +
I'll create a task

2021-03-22 08:16 UTC, merged