Java methods to sign in user and acquire IdToken from Cognito for Karate
BIBSYSDEV/NVA-api-testing pull request #21
Opened 2021-10-08 13:16 UTC by janbj

2021-10-08 13:22 UTC, axthosarouris commented on src/main/java/nva/api/testing/AuthenticationMethods.java
> +            return authResponse.authenticationResult().idToken();
put this into a private method

2021-10-08 13:27 UTC, axthosarouris requested changes

2021-10-08 13:27 UTC, axthosarouris commented on src/test/java/tests/TestsRunner.java
> +    void test() {
if this test is supposed to run all tests name it runAllCucumberTests.

2021-10-08 13:27 UTC, axthosarouris commented on src/test/java/tests/customers/CustomersRunner.java
> +    void test() {
same

2021-10-09 09:28 UTC, brinxmat requested changes
Can you also remove the .vscode directory, it's included in .gitignore, but has been committed previously.

Is karate.jar needed, or is this covered in gradle's deps?

Update the github workflow — the directory `tests` has moved to `src/test/java/tests`, I guess

2021-10-09 09:28 UTC, brinxmat commented on build.gradle
> +    // mavenLocal()
?

2021-10-09 09:28 UTC, brinxmat commented on src/test/java/karate-config.js
> +  let authentication = Java.type('nva.api.testing.AuthenticationMethods');
```
function setup() {
  const authentication = Java.type('nva.api.testing.AuthenticationMethods')
  const username = karate.properties.username
  const client_id = karate.properties.clientId
  const user_pool_id = karate.properties.userPoolId
  return {
    BEARER_TOKEN: authentication.getIdToken(username, client_id, user_pool_id),
    SERVER_URL: karate.properties.serverUrl
  }
}
```

2021-10-11 08:15 UTC, janbj commented on src/main/java/nva/api/testing/AuthenticationMethods.java
> +            return authResponse.authenticationResult().idToken();
@axthosarouris what part of code?

2021-10-11 10:18 UTC, axthosarouris approved these changes

2021-10-11 11:39 UTC, brinxmat approved these changes

2021-10-11 12:00 UTC, merged