Remove nva test data, create initial test
BIBSYSDEV/NVA-api-testing pull request #6
Opened 2021-02-11 13:09 UTC by brinxmat

- Removed previous test data as it is not clear what is expected yet
- Add initial test for what *is* known

2021-02-15 06:45 UTC, Eiriknil approved these changes, later dismissed

2021-02-18 12:59 UTC, axthosarouris requested changes
Problem should return a Requestid as well, to help in debugging

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +  Scenario Outline: GET non-existing resource
Scenario Outline: Requesting non-existing resource returns not found error

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +    And the Cristin API response takes longer than 2 seconds
copy-paste error

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +  Scenario Outline: Query with method non-GET gives Method error
fix title

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +    And the Cristin API response takes longer than 2 seconds
copy-paste error

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +    And match response == '{"title": "Gateway Timeout", "status": 504, "detail": "Your request cannot be processed at this time because the upstream server response took too long'}
copy-paste error

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +    Given url <URL>
URL -> BadRequestUrl

2021-02-18 12:59 UTC, axthosarouris commented on tests/nva/project.feature
> +    * configure headers = { 'Accept': <Content-type>, 'Authorization: Basic ' + token }
Content-type -> Unacceptable-Content-Type

2021-02-19 08:03 UTC, Eiriknil approved these changes, later dismissed

2021-02-19 11:57 UTC, axthosarouris commented on tests/nva/project.feature
> +    And match response.title == 'Gateway Timeout'
Is this the expected response title?

2021-02-19 12:16 UTC, torarnet submitted a review, later dismissed
Blir det for mye prosjektdata i søkeresultater? Er det bedre å korte ned innhold i søk og heller slå opp per prosjekt, eller er det best å ha med alt fra starten av?

2021-02-19 12:46 UTC, brinxmat commented
> Blir det for mye prosjektdata i søkeresultater? Er det bedre å korte ned innhold i søk og heller slå opp per prosjekt, eller er det best å ha med alt fra starten av?

Tenderer så klart å være enig, men i første omgang tar vi og proxyer all data da vi ikke har fått klarhet i hva bestiller faktisk ønsker seg. Da kan vi behandle JSON som JSON og ikke lage unødvendig kode før neste iterasjon.

2021-02-24 16:28 UTC, torarnet commented on test_files/nva/possible_project_structure.json
> +    "en": "<p>There is a need for improved and less costly methods for assessing the firefighters fitness in Norway due to the numerous scattered fire stations and the long distances to central uniti
Should tag <p> be added to all the text fields?

2021-02-24 16:35 UTC, torarnet commented on test_files/nva/project_search_get_result.json
> +  "query": "projects?title=__query_text__",
How is "query" related to "id"? id says "project/search?..." while query says "projects?.."

2021-02-24 16:47 UTC, torarnet commented on tests/nva/project.feature
> +      | JSON_MEDIA_TYPE    |
Does this test framework have problems with more than one newline between Examples and Scenario?

2021-02-24 16:50 UTC, torarnet approved these changes
I will approve but there should be more people to QA as my knowledge of integration testing is limited, and as we discussed earlier, the data models may have to go through more iterations later

2021-02-26 14:45 UTC, brinxmat commented on test_files/nva/possible_project_structure.json
> +    "en": "<p>There is a need for improved and less costly methods for assessing the firefighters fitness in Norway due to the numerous scattered fire stations and the long distances to central uniti
This is just raw data from Cristin, just return as is.

2021-02-26 14:46 UTC, brinxmat commented on test_files/nva/project_search_get_result.json
> +  "query": "projects?title=__query_text__",
id is the NVA-endpoint, query is the cristin endpoint (these will be refactored later)

2021-02-26 14:46 UTC, brinxmat commented on tests/nva/project.feature
> +      | JSON_MEDIA_TYPE    |
That is a question for @Eiriknil

2021-02-28 11:58 UTC, axthosarouris approved these changes

2021-03-01 07:19 UTC, Eiriknil approved these changes

2021-03-03 14:14 UTC, merged