Tests for users internal API
BIBSYSDEV/NVA-api-testing pull request #7
Opened 2021-02-26 07:50 UTC by Eiriknil

2021-02-26 10:37 UTC, brinxmat requested changes

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        * def notExistingUser = 'not-existing-user'
I guess this is non-existent-user as 'not-existing-user' implies that the usr is going to be created

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        And match response.title == 'Not Found'
Assert that the response contains the status too in all cases, which it should

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +    Scenario: POST user allready exist
Already

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        And match response.detail == 'JSON object is missing a type attribute'
missing, really?

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +    Scenario: POST wrong role type attribute
This repeats the previous scenario

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        Given path putUser
Missing scenario description on the two following scenarios

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        And method GET
And or When? Following pattern above…

2021-02-26 10:37 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        Given path putUser
I guess we're updating the same resource here, but the scenarios become dependent on each other, which we don't want

2021-02-26 11:12 UTC, Eiriknil commented on tests/users_internal/users_internal.feature
> +        And match response.detail == 'JSON object is missing a type attribute'
That's what the status says

2021-02-26 11:13 UTC, Eiriknil commented on tests/users_internal/users_internal.feature
> +    Scenario: POST wrong role type attribute
Different type element, first one is for the User, this is for the Role

2021-02-26 11:15 UTC, Eiriknil commented on tests/users_internal/users_internal.feature
> +        Given path putUser
Technicaly the same Scenario, testing to see that the User has been updated. I guess I should just add these to the Then part of the Scenario

2021-02-26 12:27 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +        And match response.detail == 'JSON object is missing a type attribute'
That sounds like a bug to me :D

2021-02-26 12:27 UTC, brinxmat approved these changes, later dismissed

2021-02-28 12:11 UTC, axthosarouris requested changes
I think the scenario titles are too short. I think that the scenario title should describe the expectation of the test, so that a) The reader does not have to read the scenario to understand the fundamental expectations of the test, and b) errors in the test code can be easily traced. E.g. copy-pasting the wrong error code.

2021-02-28 12:11 UTC, axthosarouris commented on tests/users_internal/users_internal.feature
> +    Scenario: GET user success
Scenario descriptions should be more detailed:  `GET returns user-details and status OK when requesting existing user and client is authorized'

2021-02-28 12:11 UTC, axthosarouris commented on tests/users_internal/users_internal.feature
> +    Scenario: GET user not found
Get returns notFound when client requests non-exisiting user'

2021-03-01 06:52 UTC, Eiriknil commented on tests/users_internal/users_internal.feature
> +    Scenario: GET user success
Agree, I will update descriptions to be more detailed.

2021-03-01 10:24 UTC, axthosarouris approved these changes

2021-03-01 13:36 UTC, janbj approved these changes

2021-03-02 08:19 UTC, merged