API tests for Customers api
BIBSYSDEV/NVA-api-testing pull request #9
Opened 2021-03-05 07:56 UTC by Eiriknil

2021-03-05 09:20 UTC, janbj commented on auth.json
> +    "BEARER_TOKEN": "eyJraWQiOiJGWjJod0htc3pVNGZIN0NDdXI4QkVzRjV2SkRuNmlDWnRNOXR4Rkc2dHlrPSIsImFsZyI6IlJTMjU2In0.eyJjdXN0b206ZmVpZGVUYXJnZXRlZElkIjoiYXBpLXRlc3QtdXNlckB0ZXN0Lm5vIiwic3ViIjoiNzA2Yzc2ZG
How does this work? Is Cognito set up to accept a static token?

2021-03-05 09:20 UTC, janbj commented on karate-config.js
> +    BEARER_TOKEN: auth.BEARER_TOKEN,
Maybe read from env var?

2021-03-05 10:07 UTC, Eiriknil commented on auth.json
> +    "BEARER_TOKEN": "eyJraWQiOiJGWjJod0htc3pVNGZIN0NDdXI4QkVzRjV2SkRuNmlDWnRNOXR4Rkc2dHlrPSIsImFsZyI6IlJTMjU2In0.eyJjdXN0b206ZmVpZGVUYXJnZXRlZElkIjoiYXBpLXRlc3QtdXNlckB0ZXN0Lm5vIiwic3ViIjoiNzA2Yzc2ZG
I have a python script that logs in and update the Bearer token. This is not optimal, but haven't found a better solution yet

2021-03-05 10:07 UTC, Eiriknil commented on karate-config.js
> +    BEARER_TOKEN: auth.BEARER_TOKEN,
Tried that, was hard to find a simple solution. I will try to find a better solution.

2021-03-05 10:16 UTC, axthosarouris requested changes

2021-03-05 10:16 UTC, axthosarouris commented on login_aws.py
> +                return email
refactor to method to be clearer what you are looking for. e.g. __search_user_in_user_list__

2021-03-05 10:16 UTC, axthosarouris commented on login_aws.py
> +            json.dump({'BEARER_TOKEN': bearer_token}, outfile, indent=4)
refactor to method

2021-03-05 12:38 UTC, brinxmat requested changes

2021-03-05 12:38 UTC, brinxmat commented on tests/customers/customers.feature
> +     And match response contains getCustomerIdSuccessResponse
Indent

2021-03-05 12:38 UTC, brinxmat commented on tests/registrations/registrations.feature
> +    Scenario: GET returns Registration and status Ok when requesting existing Registration
Maybe not part of this PR?

2021-03-05 12:38 UTC, brinxmat commented on tests/users_internal/users_internal.feature
> +    Scenario: PUT returns status Accepted when updating an existing User with correct payload
Accepted != 200

2021-03-05 12:39 UTC, Eiriknil commented on tests/registrations/registrations.feature
> +    Scenario: GET returns Registration and status Ok when requesting existing Registration
Yeah, forgot to switch branch there, will remove it

2021-03-08 07:59 UTC, axthosarouris approved these changes

2021-03-08 08:55 UTC, brinxmat approved these changes

2021-03-08 10:01 UTC, janbj approved these changes

2021-03-12 06:29 UTC, merged